# Generated by Django 4.0 on 2022-01-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boldmann_wears', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolducts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/product_listed_image'),
        ),
        migrations.AddField(
            model_name='bolducts',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
