# Generated by Django 4.0 on 2022-01-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boldmann_wears', '0003_bolducts_category_bolducts_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolducts',
            name='category',
            field=models.CharField(choices=[('Boots', 'Boots'), ('Monkstrap', 'Monkstrap'), ('Brogues', 'Brogues'), ('Leather slides', 'Leather slides'), ('Oxfords', 'Oxfords'), ('Loafers', 'Loafers'), ('Leather mules', 'Leather mules')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bolducts',
            name='label',
            field=models.CharField(choices=[('New Arrival', 'New Arrival'), ('Out of Stock', 'Out of Stock')], max_length=50),
        ),
    ]
